spring:
  application:
    name: eureka-feign
app:
  hostname: localhost
server:
  port: 8086
eureka:
  client:
#    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrl: https://${app.hostname}:${server.port}/info
    healthCheckUrl: https://${app.hostname}:${server.port}/health
    instance_id: ${app.hostname}:${server.port}:${spring.application.name}

