spring:
  application:
    name: eureka-provider
  redis:
    cluster:
      nodes: 47.115.3.241:6388,47.115.3.241:6384, 47.115.3.241:6383, 47.115.3.241:6385, 47.115.3.241:6384,47.115.3.241:6382,81.71.31.103:6382,81.71.31.103:6384,47.115.3.241:6389
      max-redirects: 4
    jedis:
      pool:
        max-wait: 10000ms
        minIdle: 1
app:
  hostname: localhost
server:
  port: 8082
eureka:
  client:
#    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrl: https://${app.hostname}:${server.port}/info
    healthCheckUrl: https://${app.hostname}:${server.port}/health
    instance_id: ${app.hostname}:${server.port}:${spring.application.name}


