spring:
  application:
    name: eureka-provider
  kafka:
    bootstrap-servers: www.qxlearn.work:9092
    producer:
      acks: -1
      retries: 3
    consumer:
#      enable-auto-commit: false
      auto-offset-reset: latest
    listener:
      concurrency: 2
      ack-mode: batch
app:
  hostname: localhost
server:
  port: 8084
eureka:
  client:
#    registerWithEureka: false
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrl: https://${app.hostname}:${server.port}/info
    healthCheckUrl: https://${app.hostname}:${server.port}/health
    instance_id: ${app.hostname}:${server.port}:${spring.application.name}

#server:
#  port: 8080